apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-utility-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: backstage=jaimehenao8126/backstage-production:latest
    argocd-image-updater.argoproj.io/backstage.update-strategy: latest
    argocd-image-updater.argoproj.io/backstage.allow-tags: regexp:^\d+\.\d+\.\d+$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: "kustomization:helm/backstage-utility"
spec:
  project: default
  source:
    repoURL: https://github.com/Portfolio-jaime/BACKSTAGE-KIND.git
    targetRevision: main
    path: helm/backstage-utility
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: global.environment
          value: dev
        - name: backstage.image.tag
          value: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage-utility
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
        - /spec/template/spec/containers/0/image
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /spec/minReplicas
        - /spec/maxReplicas
        - /status
  info:
    - name: 'Environment'
      value: 'Development'
    - name: 'Repository'
      value: 'https://github.com/Portfolio-jaime/BACKSTAGE-KIND-MIGRATION'
    - name: 'Documentation'
      value: 'https://github.com/Portfolio-jaime/BACKSTAGE-KIND-MIGRATION/blob/main/README.md'